#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-snakeyaml
Version  : 1.12
Release  : 4
URL      : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar
Source0  : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar
Source1  : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.12/snakeyaml-1.12.pom
Source2  : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.15/snakeyaml-1.15.jar
Source3  : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.15/snakeyaml-1.15.pom
Source4  : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.16/snakeyaml-1.16.jar
Source5  : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.16/snakeyaml-1.16.pom
Source6  : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar
Source7  : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.17/snakeyaml-1.17.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-snakeyaml-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-snakeyaml package.
Group: Data

%description data
data components for the mvn-snakeyaml package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12/snakeyaml-1.12.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.15
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.15/snakeyaml-1.15.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.15
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.15/snakeyaml-1.15.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.16
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.16/snakeyaml-1.16.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.16
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.16/snakeyaml-1.16.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.17
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.17
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar
/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12/snakeyaml-1.12.pom
/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.15/snakeyaml-1.15.jar
/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.15/snakeyaml-1.15.pom
/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.16/snakeyaml-1.16.jar
/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.16/snakeyaml-1.16.pom
/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar
/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.17/snakeyaml-1.17.pom
