#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-snakeyaml
Version  : 1.12
Release  : 2
URL      : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar
Source0  : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar
Source1  : https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.12/snakeyaml-1.12.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-snakeyaml-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-snakeyaml package.
Group: Data

%description data
data components for the mvn-snakeyaml package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12/snakeyaml-1.12.jar
/usr/share/java/.m2/repository/org/yaml/snakeyaml/1.12/snakeyaml-1.12.pom
